name: AI Code Reviewer

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions: write-all
jobs:
  review:
    if: github.event.pull_request && startsWith(github.event.pull_request.title, '[AI REVIEW]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Review
        uses: ming8525/ai-code-reviewer@develop
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4-1106-preview"
          EXCLUDE_FILES: "dist/**, **/*.json, **/*.md, **/*.js"
          MAX_ALLOWED_LINES: 200
          MAX_RETURNED_COMMENTS: 10